### PR TITLE
No longer pin m3x to a certain version in glide

### PR DESCRIPTION
**Pull request by cw9**
Pinning m3x to a version seems unnecessary to me

@xichen2020 @robskillington

### CODE REVIEW

**Comment by xichen2020** [comment]
hm why? If we don't pin it, every time we run glide update it'll automatically pick up the latest, which may not be what we want

**Comment by cw9** [comment]
Hmm, we should make sure master of m3x always work no? What I want now is to add instrument subpackage to it, I could just add that, but felt we don't need to pin m3x version thus removed the whole pin.

**Comment by xichen2020** [comment]
Yeah, I'm more worried about the scenario where m3cluster relies on an old version of m3x, which works just fine, and the tip of master in m3x has some backward-incompatible changes, so if we update the deps of m3cluster, we'll pick those changes up, which we may or may not want to (especially in the situation of emergency deploys)

**Comment by cw9** [comment]
Yeah, that's true, I'll just add a subpackage and use current tip of master with it

**Comment by cw9** [comment]
Actually I'll just do the glide update in the pr with code change

**Pull request closed without merging**
